# Template Repository Configuration
name: Node.js Project Template
description: A template for Node.js projects with complete CI/CD setup

# Files to include when repository is used as a template
includeFiles:
  - .github/**/*
  - .eslintrc.json
  - .stylelintrc.json
  - .markdownlint.json
  - .prettierrc
  - tsconfig.json
  - package.json
  - CONTRIBUTING.md
  - SECURITY.md
  - LICENSE
  - README.md

# Default branch protection rules
branchProtection:
  main:
    required_status_checks:
      - Codacy Static Code Analysis
      - CodeQL
      - ci/circleci: build
      - ci/circleci: lint
      - ci/circleci: test
    required_pull_request_reviews: true
    enforce_admins: true

# Default labels
labels:
  - name: bug
    color: d73a4a
  - name: enhancement
    color: a2eeef
  - name: documentation
    color: 0075ca
  - name: security
    color: ee0701

# Default issue templates
issueTemplates:
  - name: Bug Report
    about: Create a report to help us improve
  - name: Feature Request
    about: Suggest an idea for this project

# Default pull request template
pullRequestTemplate: true
