---
engines:
  rubocop:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - typescript
        - javascript
  metrics:
    enabled: true
  coverage:
    enabled: true
  eslint:
    enabled: true
  tslint:
    enabled: true
exclude_paths:
  - 'node_modules/**'
  - 'dist/**'
  - '.git/**'
  - 'coverage/**'
  - 'docs/**'
  - '*.min.js'
  - '*.test.{ts,tsx,js,jsx}'
  - '*.spec.{ts,tsx,js,jsx}'
  - '.next/**'
  - 'build/**'
  - '.cache/**'
  - 'vite.config.ts'
  - '*.d.ts'