version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  plugins = ["react"]
  dialect = "typescript"
  style_guide = "standard"

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

exclude_patterns = [
  "node_modules/**",
  "dist/**",
  "coverage/**",
  "**/*.test.{js,jsx,ts,tsx}",
  "**/__tests__/**"
]
