# Organization Secrets Required for Workflows
# Copy this file to your GitHub Organization Settings > Secrets and Variables > Actions

# Code Quality & Security
CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

# Deployment
VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# Monitoring
GRAFANA_CLOUD_TOKEN: ${{ secrets.GRAFANA_CLOUD_TOKEN }}

# NPM Registry (if using private packages)
NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
