name: Snyk Security

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays

permissions:
  contents: read
  security-events: write
  pull-requests: read

jobs:
  security:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions@v1
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3.22.12
        with:
          sarif_file: snyk.sarif
          category: snyk
